data <- read.table("household_power_consumption.txt", sep=";", na.strings="?",  header=TRUE)
subsetted <- filter(data, Date == "2/2/2007" | Date == "1/2/2007")
subsetted$Date <- strptime(paste(subsetted$Date, subsetted$Time), format = "%d/%m/%Y %H:%M:%S")
png("plot3.png")
with(subsetted, plot(Date, Sub_metering_1, type = "l", xlab="", ylab="Global Active Power (kilowatts)"))
par(new=T)
with(subsetted, lines(Date, Sub_metering_2, col="red", type = "l", xlab="", ylab=""))
par(new=T)
with(subsetted, lines(Date, Sub_metering_3, col="blue", type = "l", xlab = "", ylab = ""))
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3") , lty=1, col=c('black', 'red', 'blue'), cex=.9)
graphics.off()
